apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: traefik-logs
  namespace: longhorn-system
spec:
  size: "1073741824"
  accessMode: rmx
  numberOfReplicas: 3
  staleReplicaTimeout: 2880
  fromBackup: ""
