apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    volumeHandle: traefik-logs
  persistentVolumeReclaimPolicy: Retain
