deployment:
  enabled: true
  kind: Deployment
  replicas: 3 

kubernetesCRD:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: null
  type: RollingUpdate

ports:
  web:
    port: 80
  websecure:
    port: 443

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

dashboard:
  enabled: true
