deployment:
  kind: DaemonSet
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.43.0.10
      - 8.8.8.8
    searches:
      - svc.cluster.local
      - cluster.local

#resources:
#  requests:
#    cpu: "250m"

hostNetwork: true

kubernetesCRD:
  enabled: true

tolerations:
  - operator: "Exists"

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: null
  type: RollingUpdate

ports:
  web:
    port: 8080
    middlewares:
      - traefik-service-bouncer@kubernetescrd
  websecure:
    port: 8443
    middlewares:
      - traefik-service-bouncer@kubernetescrd
  traefik:
    port: 8000
    
entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"

dashboard:
  enabled: true

#persistence:
#  enabled: true
#  volumeName: traefik-logs
#  storageClass: longhorn
#  accessMode: ReadWriteMany
#  path: /logs/traefik

logs:
  access:
    enabled: true
    format: json
    #filePath: /logs/traefik/access.log
    filters:
      statuscodes: "200-299,400-599"
    bufferingSize: 0
    fields:
      headers:
        defaultMode: drop
        names:
            User-Agent: keep

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
