apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-acquis
  namespace: crowdsec-service
  labels:
    app.kubernetes.io/name: crowdsec
data:
  acquis.yaml: |
    filenames:
      - /logs/traefik/access.log
    labels:
      type: traefik
