container_runtime: containerd
agent:
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik-service
      podName: traefik-*
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
lapi:
  env:
    - name: ENROLL_KEY
      value: "CHANGEENROLLKEY"
    - name: ENROLL_INSTANCE_NAME
      value: "APPNAME-cluster"
    - name: ENROLL_TAGS
      value: "APPNAME"
