container_runtime: containerd
agent:
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik-service
      podName: traefik-*
      program: traefik
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  resources:
    requests:
      cpu: 125m
      
lapi:
  env:
    - name: ENROLL_KEY
      value: "CHANGEENROLLKEY"
    - name: ENROLL_INSTANCE_NAME
      value: "APPNAME-cluster"
    - name: ENROLL_TAGS
      value: "APPNAME"
  resources:
    requests:
      cpu: 125m

extraVolumes:
  - name: traefik-logs
    persistentVolumeClaim:
      claimName: traefik-log
      
  - name: acquis-cm
    configMap:
      name: crowdsec-acquis

extraVolumeMounts:
  - name: traefik-logs
    mountPath: /logs/traefik
    readOnly: true
    
  - name: acquis-cm
    mountPath: /etc/crowdsec/acquis.yaml
    subPath: acquis.yaml
    readOnly: true
