apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-traefik-logs
  namespace: crowdsec-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: traefik-logs
