defaultSettings:
  defaultLonghornStaticStorageClass: longhorn
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  backupTarget: ""
  backupTargetCredentialSecret: ""
  nfsExportOptions: "nolock,async,no_root_squash"
  defaultDataPath: /var/lib/longhorn
  createDefaultDiskLabeledNodes: true

persistence:
  defaultClass: true

longhornManager:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornDriver:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornUI:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}
