defaultSettings:
  defaultReplicaCount: 3
  defaultLonghornStaticStorageClass: longhorn
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  backupTarget: ""
  backupTargetCredentialSecret: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3

longhornManager:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornDriver:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornUI:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

ingress:
  enabled: true
  host: longhorn.domain.com
  ingressClassName: traefik
  tls: false
