defaultSettings:
  defaultReplicaCount: 3
  defaultLonghornStaticStorageClass: longhorn
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  backupTarget: ""
  backupTargetCredentialSecret: ""
  guaranteedEngineManagerCPU: 10m
  guaranteedReplicaManagerCPU: 10m
  nfsExportOptions: "nolock,async,no_root_squash"
  createDefaultDiskLabeledNodes: true

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3

longhornManager:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornDriver:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}

longhornUI:
  tolerations:
    - operator: "Exists"
  nodeSelector: {}
